# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 380d3700a98df7b7baba4b01d9e4b2753ea93a7e4e9ce201cb2154f56b7810c1b3aeefa34047307bffb6df7d22b590b42dbed30546d2e905a8e09ee6d809ceff

test:
  secret_key_base: 6a891308eede011d7e14a2145bbdb7646073bd2cf18f43cd5158c20768719a4f2b8363fc4d1c47f2c92e3a58bb4fb5219f9faf3d9da38abb56fadae3471bfea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
